#!/usr/bin/env python3
"""Check book Markdown, exact reference copies, and generated local navigation.

Uses the existing guide checker's documented Markdown subset. HTML checks use
the standard-library parser, validate local link/image/script/style targets and
fragment IDs, and flag duplicate IDs. External URLs are not fetched. This is
neither a renderer/accessibility audit nor execution of the Rust examples.
"""
from __future__ import annotations

from html.parser import HTMLParser
from pathlib import Path
import re
import sys
import tomllib
from urllib.parse import unquote, urljoin, urlsplit

ROOT = Path(__file__).resolve().parents[2]
BOOK = ROOT / "book"
SITE = BOOK / "_site"
STARTER = "moss-starter-2026-09-23.zip"
EDITION_SOURCE = "moss-book-source-2026-09-23.zip"
sys.path.insert(0, str(ROOT / "docs/tutorial/authoring"))
from check_docs import _anchors, _links, _visible_lines  # noqa: E402
from check_path_examples import tagged_example  # noqa: E402


class Page(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.ids: set[str] = set()
        self.duplicates: set[str] = set()
        self.links: list[str] = []
        self.base: str | None = None

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        attributes = dict(attrs)
        if tag == "base":
            if self.base is None:
                self.base = attributes.get("href")
            return
        identifier = attributes.get("id")
        if identifier:
            if identifier in self.ids:
                self.duplicates.add(identifier)
            self.ids.add(identifier)
        for key in ("href", "src"):
            value = attributes.get(key)
            if value:
                self.links.append(value)


def check_markdown(errors: list[str]) -> tuple[int, int]:
    files = sorted(BOOK.glob("*.md")) + sorted((BOOK / "src").rglob("*.md")) + sorted((BOOK / "editorial").rglob("*.md"))
    links = 0
    for path in files:
        lines = _visible_lines(path, errors)
        for number, destination in _links(lines, path, errors):
            url = urlsplit(destination)
            if url.scheme or url.netloc:
                continue
            links += 1
            target = (path.parent / unquote(url.path)).resolve() if url.path else path
            # These downloads are generated by the normal book build; they
            # intentionally do not live among the versioned Markdown sources.
            for name in (STARTER, STARTER + ".sha256", EDITION_SOURCE, EDITION_SOURCE + ".sha256"):
                if target == BOOK / "src/downloads" / name:
                    target = BOOK / "artifacts" / name
            if not target.is_file():
                errors.append(f"{path.relative_to(ROOT)}:{number}: missing file {destination}")
            elif url.fragment and target.suffix == ".md":
                if unquote(url.fragment) not in _anchors(_visible_lines(target, errors)):
                    errors.append(f"{path.relative_to(ROOT)}:{number}: missing anchor {destination}")
    return len(files), links


def check_examples(errors: list[str]) -> int:
    count = 0
    seen: set[str] = set()
    for chapter in sorted((BOOK / "src").rglob("*.md")):
        for marker in re.findall(r"<!-- moss-example: ([a-z0-9-]+) -->", chapter.read_text()):
            count += 1
            if marker in seen:
                errors.append(f"Repeated example marker: {marker}")
            seen.add(marker)
            if marker == "movement-v2-helper":
                source = ROOT / "docs/tutorial/today-v2.md"
                source_marker = "example: " + marker
            elif re.fullmatch(r"session-\d{2}", marker):
                candidates = list((ROOT / "docs/tutorial/path").glob(marker[-2:] + "-*.md"))
                if len(candidates) != 1:
                    errors.append(f"Cannot identify canonical source for {marker}")
                    continue
                source = candidates[0]
                source_marker = "runnable: " + marker
            else:
                errors.append(f"Unknown example marker: {marker}")
                continue
            try:
                printed = tagged_example(chapter, "moss-example: " + marker)
                canonical = tagged_example(source, source_marker)
                if printed != canonical:
                    errors.append(f"{chapter.relative_to(ROOT)}: {marker} differs from its canonical reference")
            except (ValueError, RuntimeError) as error:
                errors.append(str(error))
    if not count:
        errors.append("No marked textbook examples were found")
    return count


def check_html(errors: list[str]) -> tuple[int, int]:
    config = tomllib.loads((BOOK / "book.toml").read_text())
    prefix = config.get("output", {}).get("html", {}).get("site-url", "/")
    if not prefix.startswith("/") or not prefix.endswith("/") or prefix.startswith("//"):
        errors.append("site-url must be a root-relative directory ending in /")
        return 0, 0
    origin = "https://moss-book.invalid"
    pages: dict[Path, Page] = {}
    for path in SITE.rglob("*.html"):
        page = Page()
        page.feed(path.read_text())
        pages[path] = page
        if page.duplicates:
            errors.append(f"{path.relative_to(SITE)}: duplicate IDs {sorted(page.duplicates)}")
    if not pages:
        errors.append("No HTML build found; run sh book/scripts/book.sh build first")
    count = 0
    for path, page in pages.items():
        document_url = origin + prefix + path.relative_to(SITE).as_posix()
        base = urljoin(document_url, page.base) if page.base is not None else document_url
        base_url = urlsplit(base)
        if base_url.netloc != "moss-book.invalid" or not base_url.path.startswith(prefix):
            errors.append(f"{path.relative_to(SITE)}: HTML base escapes configured site {page.base}")
        for destination in page.links:
            url = urlsplit(destination)
            if url.scheme or url.netloc:
                continue
            count += 1
            resolved = urlsplit(urljoin(base, destination))
            if resolved.netloc != "moss-book.invalid" or not resolved.path.startswith(prefix):
                errors.append(f"{path.relative_to(SITE)}: unresolved output link {destination} (outside {prefix})")
                continue
            target = (SITE / unquote(resolved.path[len(prefix):])).resolve()
            if target.is_dir():
                target /= "index.html"
            if not target.is_relative_to(SITE) or not target.is_file():
                errors.append(f"{path.relative_to(SITE)}: unresolved output link {destination}")
            elif resolved.fragment and target in pages and unquote(resolved.fragment) not in pages[target].ids:
                errors.append(f"{path.relative_to(SITE)}: missing output fragment {destination}")
    return len(pages), count


def main() -> int:
    errors: list[str] = []
    files, markdown_links = check_markdown(errors)
    examples = check_examples(errors)
    pages, output_links = check_html(errors)
    print(f"Book: {files} Markdown files, {markdown_links} local destinations, {examples} exact reference copies.")
    print(f"Built site: {pages} HTML pages, {output_links} local destinations.")
    for error in errors:
        print(error)
    return int(bool(errors))


if __name__ == "__main__":
    raise SystemExit(main())
